### ISSUE TITLE
Issue when debugging

### ISSUE THREAD

**Issue by ghost** [startnine/filecommander#2]
![image](https://user-images.githubusercontent.com/37509156/41814672-4538d202-771a-11e8-9911-5dc4741e628b.png)

**Comment by ghost** [comment]
any help

**Comment by ghost** [comment]
System.Windows.Markup.XamlParseException
  HResult=0x80131501
  Message='The invocation of the constructor on type 'Fluent.Button' that matches the specified binding constraints threw an exception.' Line number '186' and line position '18'.
  Source=PresentationFramework
  StackTrace:
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at RibbonFileManager.MainWindow.InitializeComponent() in F:\RibbonFileManager-master (1)\RibbonFileManager-master\RibbonFileManager\MainWindow.xaml:line 1

Inner Exception 1:
TypeInitializationException: The type initializer for 'Fluent.Ribbon' threw an exception.

Inner Exception 2:
TypeInitializationException: The type initializer for 'Fluent.RibbonLocalization' threw an exception.

Inner Exception 3:
ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.

details here

**Comment by Splitwirez** [comment]
No, I'm not going to help you steal our code.

**Comment by ghost** [comment]
not what i asked
